version: '3.1'

networks:
  lan:

services:
  webserver:
    image: reverseproxy
    networks:
      - lan
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
      - "7474:7474"
    #volumes: 
    #  - $HOME/neo4j/neo4j-nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    
  core1:
    image: arm64v8/neo4j:5.12.0-enterprise
    networks:
      - lan
    ports:
      - 17474:17474
      - 7473:7473
      - 6362:6362
      - 7687:7687
      - 7688:7688
      - 5001:5001
      - 2004:2004

    volumes:
      - $HOME/neo4j/neo4j-fivetwelvebloom/conf:/conf
      - $HOME/neo4j/neo4j-fivetwelvebloom/data:/data
      - $HOME/neo4j/neo4j-fivetwelvebloom/logs:/logs
      - $HOME/neo4j/neo4j-fivetwelvebloom/plugins:/plugins
      - $HOME/neo4j/neo4j-fivetwelvebloom/metrics:/metrics
      - $HOME/neo4j/neo4j-fivetwelvebloom/import:/var/lib/neo4j/import
      - $HOME/neo4j/neo4j-fivetwelvebloom/licenses:/var/lib/neo4j/licenses
     
    environment:
      - NEO4J_AUTH=neo4j/Amish_2020_Tesla
      - NEO4J_PLUGINS='["bloom"]'
      - NEO4J_server_cluster_system__database__mode=PRIMARY
      - NEO4J_initial_server_mode__constraint=PRIMARY
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes   
      - NEO4J_server_default__advertised__address=localhost
      - NEO4J_server_http_listen__address=:17474
      - NEO4J_server_http_advertised__address=:17474
      - NEO4J_server_https_enabled=false
      - NEO4J_server_https_listen__address=:7473
      - NEO4J_server_https_advertised__address=:7473
      - NEO4J_server_bolt_listen__address=:7687
      - NEO4J_server_bolt_advertised__address=:7687
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*,bloom.*,com.neo4jh3.*,com.foursquare.*,com.neo4j.*,com.nyctaxi.*,com.snap.*,com.mediamath.*,com.freki.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*,bloom.*,com.neo4jh3.*,com.foursquare.*,com.neo4j.*,com.nyctaxi.*,com.snap.*,com.mediamath.*,com.freki.*
      - NEO4J_internal_metrics_cypher_cache_entries_enabled=true
      - NEO4J_server_metrics_enabled=true
      - NEO4J_server_metrics_filter=*
      - NEO4J_server_metrics_csv_enabled=false
      - NEO4J_server_memory_heap_initial__size=12g
      - NEO4J_server_memory_heap_max__size=12g
      - NEO4J_server_memory_pagecache_size=2g
      - NEO4J_gds_enterprise_license__file=/var/lib/neo4j/licenses/gds.lic
      - NEO4J_dbms_bloom_license__file=/var/lib/neo4j/licenses/bloom.lic
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_server_metrics_prometheus_enabled=true
      - NEO4J_server_metrics_prometheus_endpoint=localhost:2004
      - NEO4J_internal_dbms_relationship__uniqueness__constraints=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_routing_enabled=false
      - NEO4J_server_unmanaged__extension__classes=com.neo4j.bloom.server=/bloom
      - NEO4J_dbms_security_http__auth__allowlist=/,/browser.*,/bloom.*
      #- NEO4J_dbms_cluster_discovery_endpoints=127.0.0.1:5001
      #- NEO4J_server_discovery_listen__address=127.0.0.1:5001
      #- NEO4J_server_discovery_advertised__address=127.0.0.1:5001
    
